# ref https://github.com/Maecenas/ICS-15213-CSAPP3e-CMU
services:
  shark:
    build: .
    image: seinfeld/cmu-15213:latest
    container_name: cmu-15213
    volumes:
      - $PWD:/usr/src/app/
    restart: "no"
    stdin_open: true  # --interactive Keep STDIN open even if not attached (docker exec -i)
    tty: true         # --tty Allocate a pseudo-TTY (docker exec -t)
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE